### ISSUE TITLE
min scale

### ISSUE THREAD

**Issue by bloor** [Tenpi/waifu2x#15] opened 2021-10-20 19:20 UTC
For some reason setting 0.5 scale does not work for me. No errors. But also no output.

- waifu2x.upscaleImage(`${savePath}/original/${name}.png`, `${savePath}/128/${name}.png`, {noise: 3, scale: 2.0, mode: 'noise-scale'});
- waifu2x.upscaleImage(`${savePath}/original/${name}.png`, `${savePath}/64/${name}.png`, {noise: 3, scale: 1.0, mode: 'noise-scale'});
- waifu2x.upscaleImage(`${savePath}/original/${name}.png`, `${savePath}/48/${name}.png`, {noise: 3, scale: 0.75, mode: 'noise-scale'});
- waifu2x.upscaleImage(`${savePath}/original/${name}.png`, `${savePath}/32/${name}.png`, {noise: 3, scale: 0.5, mode: 'noise-scale'});

first 3 work, the last one . does not work.

**Comment by Moebytes** [comment] 2021-10-21 02:48
Can verify an issue with scale factors 0.5 and below. However I didn't write any of the upscaling/downscale algorithms so you probably want to forward this to [waifu2x-converter-cpp](https://github.com/DeadSix27/waifu2x-converter-cpp).

**Comment by Moebytes** [comment] 2022-02-10 23:55
Closing not a bug on my end

**Closed as completed by Moebytes** 2022-02-10 23:55 UTC
Labels: bug
